export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_REQUEST = "LOAD_PRODUCTS_REQUEST";
export const LOAD_PRODUCTS_FAILURE = "LOAD_PRODUCTS_FAILURE";
export const LOAD_RELATED_SUCCESS = "LOAD_RELATED_SUCCESS";
export const LOAD_RELATED_REQUEST = "LOAD_RELATED_REQUEST";
export const LOAD_RELATED_FAILURE = "LOAD_RELATED_FAILURE"


export const LOAD_PRODUCT_SUCCESS = "LOAD_PRODUCT_SUCCESS";
export const LOAD_PRODUCT_REQUEST = "LOAD_PRODUCT_REQUEST";
export const LOAD_PRODUCT_FAILURE = "LOAD_PRODUCT_FAILURE";


export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const LOAD_FILTER_PRODUCT_REQUEST = "LOAD_FILTER_PRODUCT_REQUEST"
export const LOAD_FILTER_PRODUCT_SUCCESS = "LOAD_FILTER_PRODUCT_SUCCESS"
export const LOAD_FILTER_PRODUCT_FAILURE = "LOAD_FILTER_PRODUCT_FAILURE"


//CATEGORY 
export const CATEGORY_GET = "CATEGORY_GET";
export const CATEGORY_GET_REQUEST = "CATEGORY_GET_REQUEST";
export const CATEGORY_GET_SUCCESS = "CATEGORY_GET_SUCCESS";
export const CATEGORY_GET_FAILURE = "CATEGORY_GET_FAILURE";

export const CATEGORY_ADD_REQUEST = "CATEGORY_ADD_REQUEST";
export const CATEGORY_ADD_SUCCESS = "CATEGORY_ADD_SUCCESS";
export const CATEGORY_ADD_FAILURE = "CATEGORY_ADD_FAILURE";
export const CATEGORY_ADD_RESET = "CATEGORY_ADD_RESET";



export const LOG_IN_FAILURE = "LOG_IN_FAILURE"
export const LOG_IN_REQUEST = "LOG_IN_REQUEST"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_IN_FAILURE_DELETE = "LOG_IN_FAILURE_DELETE"

export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE"
export const LOG_OUT_REQUEST = "LOG_OUT_REQUEST"
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS"

export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE"
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILURE_DELETE = "SIGN_UP_FAILURE_DELETE"

export const LOAD_MY_INFO_SUCCESS = "LOAD_MY_INFO_SUCCESS"
export const LOAD_MY_INFO_REQUEST = "LOAD_MY_INFO_REQUEST"
export const LOAD_MY_INFO_FAILURE = "LOAD_MY_INFO_FAILURE"